-- 002_fix_incidencias_identity.sql
-- Asegura que incidencias.id_incidencia sea autoincremental y ajusta la secuencia al MAX+1
-- Idempotente y seguro de re-ejecutar.

BEGIN;

DO $$
DECLARE
  seq_name text;
  mx bigint;
BEGIN
  -- Intentar obtener la secuencia/identity asociada
  SELECT pg_get_serial_sequence('public.incidencias','id_incidencia') INTO seq_name;

  IF seq_name IS NULL THEN
    -- No hay identity/serial; intentar agregar IDENTITY (crea secuencia automáticamente)
    BEGIN
      EXECUTE 'ALTER TABLE public.incidencias ALTER COLUMN id_incidencia ADD GENERATED BY DEFAULT AS IDENTITY';
      SELECT pg_get_serial_sequence('public.incidencias','id_incidencia') INTO seq_name;
    EXCEPTION WHEN others THEN
      -- Fallback: crear secuencia y setear DEFAULT manualmente
      EXECUTE 'CREATE SEQUENCE IF NOT EXISTS public.incidencias_id_incidencia_seq';
      EXECUTE 'ALTER TABLE public.incidencias ALTER COLUMN id_incidencia SET DEFAULT nextval(''public.incidencias_id_incidencia_seq'')';
      seq_name := 'public.incidencias_id_incidencia_seq';
    END;
  END IF;

  -- Ajustar la secuencia al MAX(id_incidencia)+1
  SELECT COALESCE(MAX(id_incidencia), 0) + 1 INTO mx FROM public.incidencias;
  IF seq_name IS NOT NULL THEN
    EXECUTE format('SELECT setval(%L, %s, false)', seq_name, mx);
  END IF;
END$$;

COMMIT;
